# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "^.tox*|^fabfile*|^jwtserver/settings*"
fail_fast: true
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus, --keep-percent-format]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.23.1
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2" ]
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
    - id: black
  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: local
    hooks:
      - id: export-common-requirements
        name: Export requirements/common.txt
        language: system
        pass_filenames: false
        entry: poetry export --without-hashes -o requirements/common.txt
        files: ^(pyproject.toml|poetry.lock)$
  - repo: local
    hooks:
      - id: export-dev-requirements
        name: Export requirements/dev.txt
        language: system
        pass_filenames: false
        entry: poetry export --without-hashes -o requirements/dev.txt --with dev
        files: ^(pyproject.toml|poetry.lock)$
  - repo: local
    hooks:
      - id: export-test-requirements
        name: Export requirements/test.txt
        language: system
        pass_filenames: false
        entry: poetry export -o requirements/test.txt --with test
        files: ^(pyproject.toml|poetry.lock)$
  - repo: local
    hooks:
      - id: export-preprod-requirements
        name: Export requirements/preprod.txt
        language: system
        pass_filenames: false
        entry: poetry export -o requirements/preprod.txt --with preprod
        files: ^(pyproject.toml|poetry.lock)$
  - repo: local
    hooks:
      - id: export-prod-requirements
        name: Export requirements/prod.txt
        language: system
        pass_filenames: false
        entry: poetry export -o requirements/prod.txt --with prod
        files: ^(pyproject.toml|poetry.lock)$
