# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "^.tox*|^fabfile*|^jwtserver/settings*"
fail_fast: true
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.38.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.10.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "2.2" ]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
    - id: black
