# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-26 16:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('token_api', '0002_auto_20191125_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
