# Generated by Django 4.2.27 on 2026-01-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0005_alter_authorizedservice_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorizedservice',
            options={
                'ordering': ['data__service'],
                'verbose_name': 'Authorized Service',
                'verbose_name_plural': 'Authorized Services',
            },
        ),
        migrations.AlterField(
            model_name='applicationtoken',
            name='account',
            field=models.CharField(
                blank=True,
                help_text='LDAP account to generate a token for',
                max_length=255,
            ),
        ),
    ]
